
server:
  port: 8060

#service-registry
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#zipkin 100%
management:
  tracing:
    sampling:
      probability: 1.0


#add the configs for the api-gateway where we need to indentify that all the reqs coming from here should go to where
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**  #whenever i'm callin --> /localhost:8060/employee/** ---> it should redirect all the traffic to employee-service load balancer[lb]
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**