server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#To make sure u r pulishing all the metrices to zipkin 100% [by default i won't public all the metrices]
management:
  tracing:
    sampling:
      probability: 1.0